apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-demo

  template:
    metadata:
      labels:
        app: flask-demo

    spec:
      containers:
      - name: flask-demo
        image: devopsacrlab08.azurecr.io/flask-demo:v1
        ports:
        - containerPort: 5000